apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: tugceerkaner/todo_app:build-261
        ports:
        - containerPort: 5000
