apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app-container
        image: tugceerkaner/todo_app:build-278
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: todo-app-storage
          mountPath: /app/data
      volumes:
      - name: todo-app-storage
        persistentVolumeClaim:
          claimName: todo-app-pvc
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1a  # EBS volume'unuzun olduğu zone'u burada belirtin